[workspace]
members = [
    "uvm-shim",
    "uvm-run",
]

[package]
name = "uvm-workspace"
version = "0.1.0"
edition = "2021"

authors = ["CompileOS Team <you@example.com>"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
